// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judgement_api.proto

package milano

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmotionType int32

const (
	EmotionType_Happiness      EmotionType = 0
	EmotionType_Sadness        EmotionType = 1
	EmotionType_Fear           EmotionType = 2
	EmotionType_Anger          EmotionType = 3
	EmotionType_Disgust        EmotionType = 4
	EmotionType_Surprise       EmotionType = 5
	EmotionType_Pleasure       EmotionType = 6
	EmotionType_Love           EmotionType = 7
	EmotionType_Gratitude      EmotionType = 8
	EmotionType_Congratulation EmotionType = 9
	EmotionType_Shyness        EmotionType = 10
	EmotionType_Expectation    EmotionType = 11
	EmotionType_Euphoria       EmotionType = 12
	EmotionType_Relief         EmotionType = 13
	EmotionType_Contentment    EmotionType = 14
	EmotionType_Contempt       EmotionType = 15
	EmotionType_Schadenfreude  EmotionType = 16
	EmotionType_Interest       EmotionType = 17
	EmotionType_Adoration      EmotionType = 18
	EmotionType_Motivation     EmotionType = 19
	EmotionType_Assuredness    EmotionType = 20
	EmotionType_Pride          EmotionType = 21
	EmotionType_Confidence     EmotionType = 22
	EmotionType_Inferiority    EmotionType = 23
	EmotionType_Shame          EmotionType = 24
	EmotionType_Pity           EmotionType = 25
	EmotionType_Anxiety        EmotionType = 26
	EmotionType_Regret         EmotionType = 27
	EmotionType_Envy           EmotionType = 28
	EmotionType_Desolation     EmotionType = 29
	EmotionType_Guilt          EmotionType = 30
	EmotionType_Disappointment EmotionType = 31
	EmotionType_Shock          EmotionType = 32
	EmotionType_Panic          EmotionType = 33
	EmotionType_Suffering      EmotionType = 34
	EmotionType_Vigilance      EmotionType = 35
	EmotionType_Melancholy     EmotionType = 36
	EmotionType_Awe            EmotionType = 37
	EmotionType_Hostility      EmotionType = 38
	EmotionType_Disrespect     EmotionType = 39
	EmotionType_Boredom        EmotionType = 40
	EmotionType_Discontent     EmotionType = 41
	EmotionType_Hatred         EmotionType = 42
	EmotionType_Indignation    EmotionType = 43
	EmotionType_Distrust       EmotionType = 44
	EmotionType_None           EmotionType = 99
)

var EmotionType_name = map[int32]string{
	0:  "Happiness",
	1:  "Sadness",
	2:  "Fear",
	3:  "Anger",
	4:  "Disgust",
	5:  "Surprise",
	6:  "Pleasure",
	7:  "Love",
	8:  "Gratitude",
	9:  "Congratulation",
	10: "Shyness",
	11: "Expectation",
	12: "Euphoria",
	13: "Relief",
	14: "Contentment",
	15: "Contempt",
	16: "Schadenfreude",
	17: "Interest",
	18: "Adoration",
	19: "Motivation",
	20: "Assuredness",
	21: "Pride",
	22: "Confidence",
	23: "Inferiority",
	24: "Shame",
	25: "Pity",
	26: "Anxiety",
	27: "Regret",
	28: "Envy",
	29: "Desolation",
	30: "Guilt",
	31: "Disappointment",
	32: "Shock",
	33: "Panic",
	34: "Suffering",
	35: "Vigilance",
	36: "Melancholy",
	37: "Awe",
	38: "Hostility",
	39: "Disrespect",
	40: "Boredom",
	41: "Discontent",
	42: "Hatred",
	43: "Indignation",
	44: "Distrust",
	99: "None",
}
var EmotionType_value = map[string]int32{
	"Happiness":      0,
	"Sadness":        1,
	"Fear":           2,
	"Anger":          3,
	"Disgust":        4,
	"Surprise":       5,
	"Pleasure":       6,
	"Love":           7,
	"Gratitude":      8,
	"Congratulation": 9,
	"Shyness":        10,
	"Expectation":    11,
	"Euphoria":       12,
	"Relief":         13,
	"Contentment":    14,
	"Contempt":       15,
	"Schadenfreude":  16,
	"Interest":       17,
	"Adoration":      18,
	"Motivation":     19,
	"Assuredness":    20,
	"Pride":          21,
	"Confidence":     22,
	"Inferiority":    23,
	"Shame":          24,
	"Pity":           25,
	"Anxiety":        26,
	"Regret":         27,
	"Envy":           28,
	"Desolation":     29,
	"Guilt":          30,
	"Disappointment": 31,
	"Shock":          32,
	"Panic":          33,
	"Suffering":      34,
	"Vigilance":      35,
	"Melancholy":     36,
	"Awe":            37,
	"Hostility":      38,
	"Disrespect":     39,
	"Boredom":        40,
	"Discontent":     41,
	"Hatred":         42,
	"Indignation":    43,
	"Distrust":       44,
	"None":           99,
}

func (x EmotionType) String() string {
	return proto.EnumName(EmotionType_name, int32(x))
}
func (EmotionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{0}
}

type ActionType int32

const (
	ActionType_Regular         ActionType = 0
	ActionType_Move            ActionType = 1
	ActionType_LookAt          ActionType = 2
	ActionType_PointAt         ActionType = 3
	ActionType_SubTriggerStart ActionType = 4
	ActionType_SubTriggerStop  ActionType = 5
	ActionType_ModeChange      ActionType = 6
	ActionType_QueueClear      ActionType = 7
	ActionType_EmotionChange   ActionType = 8
	ActionType_MemoryPickup    ActionType = 9
	ActionType_Attention       ActionType = 10
	ActionType_Facial          ActionType = 11
	ActionType_RelativeMove    ActionType = 12
	ActionType_FlagOn          ActionType = 13
	ActionType_FlagOff         ActionType = 14
	ActionType_IoT             ActionType = 15
	ActionType_ResetAttention  ActionType = 16
	ActionType_Wait            ActionType = 17
	ActionType_Echo            ActionType = 18
	ActionType_EmotionReaction ActionType = 19
	ActionType_Speech          ActionType = 20
	ActionType_Motion          ActionType = 21
)

var ActionType_name = map[int32]string{
	0:  "Regular",
	1:  "Move",
	2:  "LookAt",
	3:  "PointAt",
	4:  "SubTriggerStart",
	5:  "SubTriggerStop",
	6:  "ModeChange",
	7:  "QueueClear",
	8:  "EmotionChange",
	9:  "MemoryPickup",
	10: "Attention",
	11: "Facial",
	12: "RelativeMove",
	13: "FlagOn",
	14: "FlagOff",
	15: "IoT",
	16: "ResetAttention",
	17: "Wait",
	18: "Echo",
	19: "EmotionReaction",
	20: "Speech",
	21: "Motion",
}
var ActionType_value = map[string]int32{
	"Regular":         0,
	"Move":            1,
	"LookAt":          2,
	"PointAt":         3,
	"SubTriggerStart": 4,
	"SubTriggerStop":  5,
	"ModeChange":      6,
	"QueueClear":      7,
	"EmotionChange":   8,
	"MemoryPickup":    9,
	"Attention":       10,
	"Facial":          11,
	"RelativeMove":    12,
	"FlagOn":          13,
	"FlagOff":         14,
	"IoT":             15,
	"ResetAttention":  16,
	"Wait":            17,
	"Echo":            18,
	"EmotionReaction": 19,
	"Speech":          20,
	"Motion":          21,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{1}
}

type JudgementRequest struct {
	Images               []*JudgementRequest_ImageData    `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Emotions             []*JudgementRequest_EmotionValue `protobuf:"bytes,3,rep,name=emotions" json:"emotions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *JudgementRequest) Reset()         { *m = JudgementRequest{} }
func (m *JudgementRequest) String() string { return proto.CompactTextString(m) }
func (*JudgementRequest) ProtoMessage()    {}
func (*JudgementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{0}
}
func (m *JudgementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgementRequest.Unmarshal(m, b)
}
func (m *JudgementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgementRequest.Marshal(b, m, deterministic)
}
func (dst *JudgementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgementRequest.Merge(dst, src)
}
func (m *JudgementRequest) XXX_Size() int {
	return xxx_messageInfo_JudgementRequest.Size(m)
}
func (m *JudgementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgementRequest proto.InternalMessageInfo

func (m *JudgementRequest) GetImages() []*JudgementRequest_ImageData {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *JudgementRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JudgementRequest) GetEmotions() []*JudgementRequest_EmotionValue {
	if m != nil {
		return m.Emotions
	}
	return nil
}

type JudgementRequest_Rect struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Width                float32  `protobuf:"fixed32,3,opt,name=width" json:"width,omitempty"`
	Height               float32  `protobuf:"fixed32,4,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgementRequest_Rect) Reset()         { *m = JudgementRequest_Rect{} }
func (m *JudgementRequest_Rect) String() string { return proto.CompactTextString(m) }
func (*JudgementRequest_Rect) ProtoMessage()    {}
func (*JudgementRequest_Rect) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{0, 0}
}
func (m *JudgementRequest_Rect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgementRequest_Rect.Unmarshal(m, b)
}
func (m *JudgementRequest_Rect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgementRequest_Rect.Marshal(b, m, deterministic)
}
func (dst *JudgementRequest_Rect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgementRequest_Rect.Merge(dst, src)
}
func (m *JudgementRequest_Rect) XXX_Size() int {
	return xxx_messageInfo_JudgementRequest_Rect.Size(m)
}
func (m *JudgementRequest_Rect) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgementRequest_Rect.DiscardUnknown(m)
}

var xxx_messageInfo_JudgementRequest_Rect proto.InternalMessageInfo

func (m *JudgementRequest_Rect) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *JudgementRequest_Rect) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *JudgementRequest_Rect) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *JudgementRequest_Rect) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type JudgementRequest_ImageData struct {
	Label                string                 `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Bbox                 *JudgementRequest_Rect `protobuf:"bytes,2,opt,name=bbox" json:"bbox,omitempty"`
	Confidence           int32                  `protobuf:"varint,3,opt,name=confidence" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JudgementRequest_ImageData) Reset()         { *m = JudgementRequest_ImageData{} }
func (m *JudgementRequest_ImageData) String() string { return proto.CompactTextString(m) }
func (*JudgementRequest_ImageData) ProtoMessage()    {}
func (*JudgementRequest_ImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{0, 1}
}
func (m *JudgementRequest_ImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgementRequest_ImageData.Unmarshal(m, b)
}
func (m *JudgementRequest_ImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgementRequest_ImageData.Marshal(b, m, deterministic)
}
func (dst *JudgementRequest_ImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgementRequest_ImageData.Merge(dst, src)
}
func (m *JudgementRequest_ImageData) XXX_Size() int {
	return xxx_messageInfo_JudgementRequest_ImageData.Size(m)
}
func (m *JudgementRequest_ImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgementRequest_ImageData.DiscardUnknown(m)
}

var xxx_messageInfo_JudgementRequest_ImageData proto.InternalMessageInfo

func (m *JudgementRequest_ImageData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *JudgementRequest_ImageData) GetBbox() *JudgementRequest_Rect {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *JudgementRequest_ImageData) GetConfidence() int32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type JudgementRequest_EmotionValue struct {
	Type                 EmotionType `protobuf:"varint,1,opt,name=type,enum=milano.EmotionType" json:"type,omitempty"`
	Value                int32       `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JudgementRequest_EmotionValue) Reset()         { *m = JudgementRequest_EmotionValue{} }
func (m *JudgementRequest_EmotionValue) String() string { return proto.CompactTextString(m) }
func (*JudgementRequest_EmotionValue) ProtoMessage()    {}
func (*JudgementRequest_EmotionValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{0, 2}
}
func (m *JudgementRequest_EmotionValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgementRequest_EmotionValue.Unmarshal(m, b)
}
func (m *JudgementRequest_EmotionValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgementRequest_EmotionValue.Marshal(b, m, deterministic)
}
func (dst *JudgementRequest_EmotionValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgementRequest_EmotionValue.Merge(dst, src)
}
func (m *JudgementRequest_EmotionValue) XXX_Size() int {
	return xxx_messageInfo_JudgementRequest_EmotionValue.Size(m)
}
func (m *JudgementRequest_EmotionValue) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgementRequest_EmotionValue.DiscardUnknown(m)
}

var xxx_messageInfo_JudgementRequest_EmotionValue proto.InternalMessageInfo

func (m *JudgementRequest_EmotionValue) GetType() EmotionType {
	if m != nil {
		return m.Type
	}
	return EmotionType_Happiness
}

func (m *JudgementRequest_EmotionValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type JudgementResponse struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JudgementResponse) Reset()         { *m = JudgementResponse{} }
func (m *JudgementResponse) String() string { return proto.CompactTextString(m) }
func (*JudgementResponse) ProtoMessage()    {}
func (*JudgementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{1}
}
func (m *JudgementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgementResponse.Unmarshal(m, b)
}
func (m *JudgementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgementResponse.Marshal(b, m, deterministic)
}
func (dst *JudgementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgementResponse.Merge(dst, src)
}
func (m *JudgementResponse) XXX_Size() int {
	return xxx_messageInfo_JudgementResponse.Size(m)
}
func (m *JudgementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgementResponse proto.InternalMessageInfo

func (m *JudgementResponse) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type EmotionData struct {
	Type                 EmotionType `protobuf:"varint,1,opt,name=type,enum=milano.EmotionType" json:"type,omitempty"`
	Duration             int32       `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EmotionData) Reset()         { *m = EmotionData{} }
func (m *EmotionData) String() string { return proto.CompactTextString(m) }
func (*EmotionData) ProtoMessage()    {}
func (*EmotionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{2}
}
func (m *EmotionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmotionData.Unmarshal(m, b)
}
func (m *EmotionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmotionData.Marshal(b, m, deterministic)
}
func (dst *EmotionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmotionData.Merge(dst, src)
}
func (m *EmotionData) XXX_Size() int {
	return xxx_messageInfo_EmotionData.Size(m)
}
func (m *EmotionData) XXX_DiscardUnknown() {
	xxx_messageInfo_EmotionData.DiscardUnknown(m)
}

var xxx_messageInfo_EmotionData proto.InternalMessageInfo

func (m *EmotionData) GetType() EmotionType {
	if m != nil {
		return m.Type
	}
	return EmotionType_Happiness
}

func (m *EmotionData) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type EmotionDataList struct {
	List                 []*EmotionData `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EmotionDataList) Reset()         { *m = EmotionDataList{} }
func (m *EmotionDataList) String() string { return proto.CompactTextString(m) }
func (*EmotionDataList) ProtoMessage()    {}
func (*EmotionDataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{3}
}
func (m *EmotionDataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmotionDataList.Unmarshal(m, b)
}
func (m *EmotionDataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmotionDataList.Marshal(b, m, deterministic)
}
func (dst *EmotionDataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmotionDataList.Merge(dst, src)
}
func (m *EmotionDataList) XXX_Size() int {
	return xxx_messageInfo_EmotionDataList.Size(m)
}
func (m *EmotionDataList) XXX_DiscardUnknown() {
	xxx_messageInfo_EmotionDataList.DiscardUnknown(m)
}

var xxx_messageInfo_EmotionDataList proto.InternalMessageInfo

func (m *EmotionDataList) GetList() []*EmotionData {
	if m != nil {
		return m.List
	}
	return nil
}

type Action struct {
	Type                 ActionType `protobuf:"varint,1,opt,name=type,enum=milano.ActionType" json:"type,omitempty"`
	Args                 []string   `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_judgement_api_18c3083b8bed62c4, []int{4}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_Regular
}

func (m *Action) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*JudgementRequest)(nil), "milano.JudgementRequest")
	proto.RegisterType((*JudgementRequest_Rect)(nil), "milano.JudgementRequest.Rect")
	proto.RegisterType((*JudgementRequest_ImageData)(nil), "milano.JudgementRequest.ImageData")
	proto.RegisterType((*JudgementRequest_EmotionValue)(nil), "milano.JudgementRequest.EmotionValue")
	proto.RegisterType((*JudgementResponse)(nil), "milano.JudgementResponse")
	proto.RegisterType((*EmotionData)(nil), "milano.EmotionData")
	proto.RegisterType((*EmotionDataList)(nil), "milano.EmotionDataList")
	proto.RegisterType((*Action)(nil), "milano.Action")
	proto.RegisterEnum("milano.EmotionType", EmotionType_name, EmotionType_value)
	proto.RegisterEnum("milano.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("judgement_api.proto", fileDescriptor_judgement_api_18c3083b8bed62c4) }

var fileDescriptor_judgement_api_18c3083b8bed62c4 = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x72, 0x1b, 0x45,
	0x13, 0x8d, 0xfe, 0xa5, 0x96, 0x2d, 0x77, 0xc6, 0x49, 0x3e, 0x7d, 0x86, 0x04, 0x23, 0x48, 0x22,
	0x0c, 0xa5, 0x2a, 0xc2, 0x5d, 0xaa, 0xb8, 0x50, 0x2c, 0x3b, 0x36, 0x65, 0x81, 0x58, 0xb9, 0xc2,
	0x25, 0x35, 0xde, 0x6d, 0xad, 0x26, 0x5e, 0xed, 0x2c, 0x33, 0xb3, 0x8e, 0xf5, 0x10, 0xbc, 0x08,
	0x8f, 0xc1, 0x03, 0xf0, 0x4c, 0x54, 0xcf, 0xae, 0x1c, 0x25, 0x55, 0xa9, 0xe2, 0x4e, 0xdd, 0x73,
	0xe6, 0xf4, 0x39, 0x3d, 0xc7, 0x6b, 0xd8, 0x7f, 0x9b, 0x47, 0x31, 0xad, 0x28, 0x75, 0xbf, 0xcb,
	0x4c, 0x8d, 0x32, 0xa3, 0x9d, 0x16, 0xcd, 0x95, 0x4a, 0x64, 0xaa, 0x07, 0x7f, 0xd7, 0x00, 0x7f,
	0xda, 0x9c, 0x07, 0xf4, 0x47, 0x4e, 0xd6, 0x89, 0x97, 0xd0, 0x54, 0x2b, 0x19, 0x93, 0xed, 0x57,
	0x0e, 0x6b, 0xc3, 0xee, 0x8b, 0xc1, 0xa8, 0x40, 0x8f, 0x3e, 0x46, 0x8e, 0xce, 0x19, 0x36, 0x91,
	0x4e, 0x06, 0xe5, 0x0d, 0xd1, 0x87, 0xd6, 0x8a, 0xac, 0x95, 0x31, 0xf5, 0xab, 0x87, 0x95, 0x61,
	0x27, 0xd8, 0x94, 0x62, 0x0c, 0x6d, 0x5a, 0x69, 0xa7, 0x74, 0x6a, 0xfb, 0x35, 0xcf, 0xfb, 0xf4,
	0x93, 0xbc, 0x27, 0x05, 0xf0, 0x8d, 0x4c, 0x72, 0x0a, 0xee, 0xae, 0x1d, 0xcc, 0xa0, 0x1e, 0x50,
	0xe8, 0xc4, 0x0e, 0x54, 0x6e, 0xfb, 0x95, 0xc3, 0xca, 0xb0, 0x1a, 0x54, 0x6e, 0xb9, 0x5a, 0xfb,
	0x61, 0xd5, 0xa0, 0xb2, 0x16, 0x0f, 0xa0, 0xf1, 0x4e, 0x45, 0x6e, 0xd9, 0xaf, 0xf9, 0x4e, 0x51,
	0x88, 0x47, 0xd0, 0x5c, 0x92, 0x8a, 0x97, 0xae, 0x5f, 0xf7, 0xed, 0xb2, 0x3a, 0x70, 0xd0, 0xb9,
	0xf3, 0xc0, 0x57, 0x13, 0x79, 0x45, 0x89, 0xa7, 0xee, 0x04, 0x45, 0x21, 0xbe, 0x87, 0xfa, 0xd5,
	0x95, 0xbe, 0xf5, 0x13, 0xba, 0x2f, 0x1e, 0x7f, 0x52, 0x33, 0x2b, 0x0b, 0x3c, 0x54, 0x3c, 0x01,
	0x08, 0x75, 0xba, 0x50, 0x11, 0xa5, 0x21, 0x79, 0x21, 0x8d, 0x60, 0xab, 0x73, 0x30, 0x85, 0x9d,
	0x6d, 0x87, 0xe2, 0x39, 0xd4, 0xdd, 0x3a, 0x23, 0x3f, 0xb7, 0xf7, 0x62, 0x7f, 0x33, 0xa2, 0xc4,
	0x5c, 0xae, 0x33, 0x0a, 0x3c, 0x80, 0x15, 0xde, 0xf0, 0x0d, 0x2f, 0xa6, 0x11, 0x14, 0xc5, 0xe0,
	0x47, 0xb8, 0xbf, 0xa5, 0xc6, 0x66, 0x3a, 0xb5, 0x24, 0x86, 0xd0, 0x92, 0x61, 0xb1, 0xed, 0xe2,
	0x15, 0x7b, 0x1b, 0xda, 0xb1, 0x6f, 0x07, 0x9b, 0xe3, 0x41, 0x00, 0xdd, 0x72, 0x92, 0xdf, 0xc2,
	0x7f, 0x16, 0x73, 0x00, 0xed, 0x28, 0x37, 0x92, 0xbb, 0xa5, 0x9e, 0xbb, 0x7a, 0xf0, 0x12, 0xf6,
	0xb6, 0x38, 0x2f, 0x94, 0x75, 0xcc, 0x9b, 0x28, 0xeb, 0x4a, 0x35, 0x1f, 0xf3, 0xfa, 0x10, 0x79,
	0xc0, 0x60, 0x02, 0xcd, 0x42, 0xa2, 0x78, 0xf6, 0x81, 0x14, 0xf1, 0xa1, 0x81, 0x2d, 0x25, 0x02,
	0xea, 0xd2, 0xc4, 0xb6, 0x5f, 0x3d, 0xac, 0x0d, 0x3b, 0x81, 0xff, 0x7d, 0xf4, 0x67, 0xe3, 0xce,
	0x16, 0x23, 0xc5, 0x2e, 0x74, 0xce, 0x64, 0x96, 0xa9, 0x94, 0xac, 0xc5, 0x7b, 0xa2, 0x0b, 0xad,
	0xb9, 0x8c, 0x7c, 0x51, 0x11, 0x6d, 0xa8, 0x9f, 0x92, 0x34, 0x58, 0x15, 0x1d, 0x68, 0x8c, 0xd3,
	0x98, 0x0c, 0xd6, 0x18, 0x31, 0x51, 0x36, 0xce, 0xad, 0xc3, 0xba, 0xd8, 0x81, 0xf6, 0x3c, 0x37,
	0x99, 0x51, 0x96, 0xb0, 0xc1, 0xd5, 0x2c, 0x21, 0x69, 0x73, 0x43, 0xd8, 0xe4, 0xdb, 0x17, 0xfa,
	0x86, 0xb0, 0xc5, 0x33, 0x5e, 0xf3, 0x02, 0x5c, 0x1e, 0x11, 0xb6, 0x85, 0x80, 0xde, 0xb1, 0x4e,
	0x63, 0x23, 0x5d, 0x9e, 0xf8, 0xb5, 0x60, 0xc7, 0xcf, 0x5d, 0xae, 0xfd, 0x5c, 0x10, 0x7b, 0xd0,
	0x3d, 0xb9, 0xcd, 0x28, 0x74, 0xc5, 0x69, 0x97, 0x89, 0x4f, 0xf2, 0x6c, 0xa9, 0x8d, 0x92, 0xb8,
	0x23, 0x00, 0x9a, 0x01, 0x25, 0x8a, 0x16, 0xb8, 0xcb, 0xd0, 0x63, 0x9d, 0x3a, 0x4a, 0x1d, 0xbf,
	0x32, 0xf6, 0x18, 0xea, 0x1b, 0xab, 0xcc, 0xe1, 0x9e, 0xb8, 0x0f, 0xbb, 0xf3, 0x70, 0x29, 0x23,
	0x4a, 0x17, 0x86, 0x78, 0x3a, 0x32, 0xe0, 0x3c, 0x75, 0x64, 0xc8, 0x3a, 0xbc, 0xcf, 0xd2, 0xc6,
	0x91, 0x2e, 0x5e, 0x07, 0x85, 0xe8, 0x01, 0x4c, 0xb5, 0x53, 0x37, 0x45, 0xbd, 0xcf, 0xf4, 0x63,
	0xcb, 0x7e, 0x8a, 0x95, 0x3c, 0xe0, 0x45, 0xcc, 0x8c, 0x8a, 0x08, 0x1f, 0x32, 0xf6, 0xf8, 0x2e,
	0xbb, 0xf8, 0x88, 0xb1, 0xe7, 0xe9, 0x82, 0x8c, 0xd2, 0x46, 0xb9, 0x35, 0xfe, 0x8f, 0xb1, 0xf3,
	0xa5, 0x5c, 0x11, 0xf6, 0x79, 0x17, 0x33, 0x6e, 0xfe, 0x9f, 0x8d, 0x8e, 0xd3, 0x5b, 0x45, 0x6e,
	0x8d, 0x07, 0x85, 0x93, 0xd8, 0x90, 0xc3, 0xcf, 0x18, 0x72, 0x92, 0xde, 0xac, 0xf1, 0x73, 0x26,
	0x9e, 0x90, 0xd5, 0xe5, 0x6e, 0x1e, 0x33, 0xcf, 0xeb, 0x5c, 0x25, 0x0e, 0x9f, 0xf0, 0xea, 0x26,
	0xca, 0xca, 0x2c, 0xd3, 0xaa, 0x74, 0xfc, 0x45, 0x31, 0x46, 0x87, 0xd7, 0x78, 0xe8, 0xd5, 0xc9,
	0x54, 0x85, 0xf8, 0x25, 0x1b, 0x9b, 0xe7, 0x0b, 0x96, 0x93, 0xc6, 0x38, 0xe0, 0xf2, 0x8d, 0x8a,
	0x39, 0x27, 0x21, 0xe1, 0x57, 0xde, 0x27, 0x71, 0xb1, 0xd4, 0xc9, 0x1a, 0xbf, 0x16, 0x2d, 0xa8,
	0x8d, 0xdf, 0x11, 0x3e, 0xf5, 0x71, 0xd0, 0xd6, 0xa9, 0x84, 0xd5, 0x3e, 0xf3, 0x52, 0x94, 0x35,
	0x64, 0xf9, 0x35, 0xf0, 0x39, 0xab, 0x7f, 0xa5, 0x0d, 0x45, 0x7a, 0x85, 0xc3, 0xf2, 0x30, 0x2c,
	0xd6, 0x8f, 0xdf, 0xb0, 0x9b, 0x33, 0xe9, 0x0c, 0x45, 0x78, 0x54, 0x2c, 0x23, 0x52, 0x71, 0x5a,
	0x98, 0xf8, 0x96, 0xd7, 0x3e, 0x51, 0xd6, 0x19, 0xce, 0xcd, 0x77, 0x6c, 0xf6, 0x67, 0x9d, 0x12,
	0x86, 0x47, 0xff, 0x54, 0x01, 0xde, 0x07, 0x97, 0x07, 0x04, 0x14, 0xe7, 0x89, 0x34, 0x78, 0x8f,
	0x51, 0x53, 0x4e, 0x50, 0x85, 0xa9, 0x2f, 0xb4, 0xbe, 0x1e, 0x3b, 0xac, 0x32, 0x64, 0xc6, 0xf6,
	0xc7, 0x0e, 0x6b, 0x62, 0x1f, 0xf6, 0xe6, 0xf9, 0xd5, 0xa5, 0x51, 0x71, 0x4c, 0x66, 0xee, 0xa4,
	0xe1, 0x54, 0x0a, 0xe8, 0x6d, 0x37, 0x75, 0x86, 0x8d, 0xe2, 0x65, 0x23, 0x3a, 0x5e, 0xca, 0x34,
	0xe6, 0x74, 0xf6, 0x00, 0x7e, 0xcd, 0x29, 0xa7, 0xe3, 0x84, 0x13, 0xde, 0xe2, 0xa4, 0x94, 0x7f,
	0x16, 0x25, 0xa4, 0x2d, 0x10, 0x76, 0xa6, 0xb4, 0xd2, 0x66, 0x3d, 0x53, 0xe1, 0x75, 0x9e, 0x61,
	0xc7, 0xa7, 0xc5, 0xb1, 0x5b, 0xf6, 0x04, 0xac, 0xea, 0x54, 0x86, 0x4a, 0x26, 0xd8, 0x65, 0x70,
	0x40, 0xfc, 0x64, 0x37, 0xe4, 0x35, 0xfb, 0x98, 0x9e, 0x26, 0x32, 0xfe, 0x25, 0xc5, 0x5d, 0xd6,
	0xec, 0x7f, 0x2f, 0x16, 0xd8, 0xe3, 0x65, 0x9f, 0xeb, 0x4b, 0xdc, 0x63, 0x9d, 0x01, 0x59, 0x72,
	0xef, 0x39, 0x91, 0x3d, 0xff, 0x26, 0x15, 0x47, 0x93, 0x03, 0x11, 0x2e, 0x35, 0x0a, 0x36, 0x59,
	0x6a, 0x0b, 0xa8, 0xf8, 0x3a, 0xe1, 0x3e, 0xd3, 0xcf, 0x33, 0xa2, 0x70, 0x89, 0x0f, 0xf8, 0xf7,
	0xd4, 0x9f, 0xe3, 0xc3, 0x57, 0x47, 0xd0, 0x7f, 0x9b, 0x8d, 0x42, 0x3d, 0x0a, 0x75, 0x1e, 0x93,
	0xd9, 0x7c, 0x1c, 0x22, 0xe9, 0xe4, 0x59, 0xed, 0xaf, 0x6a, 0x77, 0x5a, 0xd4, 0xfc, 0x61, 0xb9,
	0x6a, 0xfa, 0xff, 0x7a, 0x3f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xf1, 0x19, 0x22, 0x0c,
	0x07, 0x00, 0x00,
}
